-- Seed ISC2 CC exam questions (100 questions across different domains)

-- Security Principles (Domain 1)
INSERT INTO questions (question_text, option_a, option_b, option_c, option_d, correct_answer, explanation, domain) VALUES
('What is the primary goal of information security?', 'Prevent all attacks', 'Ensure confidentiality, integrity, and availability', 'Eliminate all vulnerabilities', 'Monitor all network traffic', 'B', 'The CIA triad (Confidentiality, Integrity, Availability) is the foundation of information security.', 'Security Principles'),
('Which principle ensures that data is not modified by unauthorized parties?', 'Confidentiality', 'Integrity', 'Availability', 'Non-repudiation', 'B', 'Integrity ensures data remains accurate and unaltered by unauthorized users.', 'Security Principles'),
('What does the principle of least privilege mean?', 'Users get maximum access', 'Users get minimum necessary access', 'All users have equal access', 'Administrators have all privileges', 'B', 'Least privilege means granting only the minimum access necessary to perform job functions.', 'Security Principles'),
('Which security control is detective in nature?', 'Firewall', 'Intrusion Detection System', 'Encryption', 'Access control list', 'B', 'IDS detects and alerts on suspicious activities after they occur.', 'Security Principles'),
('What is defense in depth?', 'Single strong security control', 'Multiple layers of security controls', 'Perimeter security only', 'Antivirus software', 'B', 'Defense in depth uses multiple layers of security controls to protect assets.', 'Security Principles'),
('Which is an example of a physical security control?', 'Password policy', 'Door locks', 'Firewall rules', 'Encryption', 'B', 'Door locks are physical controls that restrict physical access.', 'Security Principles'),
('What does non-repudiation ensure?', 'Data confidentiality', 'User cannot deny an action', 'Data availability', 'Access control', 'B', 'Non-repudiation ensures users cannot deny performing an action.', 'Security Principles'),
('Which authentication factor is "something you know"?', 'Fingerprint', 'Password', 'Smart card', 'Retina scan', 'B', 'Passwords are knowledge-based authentication factors.', 'Security Principles'),
('What is the purpose of encryption?', 'Detect intrusions', 'Protect data confidentiality', 'Monitor traffic', 'Control access', 'B', 'Encryption protects data confidentiality by making it unreadable without the key.', 'Security Principles'),
('Which is a preventive security control?', 'Log monitoring', 'Firewall', 'Audit trail', 'IDS alert', 'B', 'Firewalls prevent unauthorized access before it occurs.', 'Security Principles'),

-- Business Continuity (Domain 2)
('What is the primary purpose of a Business Continuity Plan?', 'Prevent all disasters', 'Ensure business operations continue during disruptions', 'Eliminate all risks', 'Reduce costs', 'B', 'BCP ensures critical business functions continue during and after disruptions.', 'Business Continuity'),
('What does RPO stand for?', 'Recovery Point Objective', 'Risk Prevention Order', 'Response Protocol Operation', 'Recovery Process Outline', 'A', 'RPO defines the maximum acceptable data loss measured in time.', 'Business Continuity'),
('What does RTO stand for?', 'Risk Transfer Option', 'Recovery Time Objective', 'Response Time Order', 'Restoration Testing Operation', 'B', 'RTO defines the maximum acceptable downtime for a system or process.', 'Business Continuity'),
('Which backup type copies only changed data since last full backup?', 'Full backup', 'Incremental backup', 'Differential backup', 'Mirror backup', 'C', 'Differential backups copy all changes since the last full backup.', 'Business Continuity'),
('What is a hot site?', 'Backup location with no equipment', 'Fully equipped backup facility', 'Office space only', 'Virtual backup', 'B', 'A hot site is a fully equipped backup facility ready for immediate use.', 'Business Continuity'),
('What should be tested regularly in a BCP?', 'Only documentation', 'Recovery procedures and plans', 'Employee attendance', 'Budget allocations', 'B', 'Regular testing ensures recovery procedures work as intended.', 'Business Continuity'),
('What is the first step in business continuity planning?', 'Purchase backup equipment', 'Conduct Business Impact Analysis', 'Train employees', 'Test the plan', 'B', 'BIA identifies critical business functions and their dependencies.', 'Business Continuity'),
('Which backup type takes the longest to restore?', 'Full backup only', 'Incremental backups', 'Differential backup', 'Mirror backup', 'B', 'Incremental backups require the last full backup plus all incremental backups.', 'Business Continuity'),
('What is a cold site?', 'Refrigerated data center', 'Backup location with basic infrastructure', 'Fully operational backup', 'Cloud-based backup', 'B', 'A cold site has basic infrastructure but no equipment or data.', 'Business Continuity'),
('What is the purpose of a disaster recovery plan?', 'Prevent disasters', 'Restore IT systems after disruption', 'Eliminate risks', 'Reduce insurance costs', 'B', 'DRP focuses on restoring IT systems and data after a disaster.', 'Business Continuity'),

-- Access Control (Domain 3)
('What is identification in access control?', 'Proving who you are', 'Claiming an identity', 'Granting permissions', 'Monitoring activities', 'B', 'Identification is claiming an identity (e.g., username).', 'Access Control'),
('What is authentication?', 'Claiming an identity', 'Proving an identity', 'Granting access', 'Logging activities', 'B', 'Authentication is proving the claimed identity is valid.', 'Access Control'),
('What is authorization?', 'Claiming identity', 'Proving identity', 'Granting permissions based on identity', 'Monitoring access', 'C', 'Authorization determines what resources an authenticated user can access.', 'Access Control'),
('Which is an example of multi-factor authentication?', 'Password only', 'Password and fingerprint', 'Two passwords', 'Username and password', 'B', 'MFA combines different types of authentication factors (knowledge + biometric).', 'Access Control'),
('What is Role-Based Access Control (RBAC)?', 'Access based on user identity', 'Access based on job role', 'Access based on location', 'Access based on time', 'B', 'RBAC grants access based on user roles within the organization.', 'Access Control'),
('What is the purpose of access control lists (ACLs)?', 'Encrypt data', 'Define who can access resources', 'Monitor network traffic', 'Backup data', 'B', 'ACLs specify which users or systems can access specific resources.', 'Access Control'),
('What is single sign-on (SSO)?', 'One password for all users', 'One authentication for multiple systems', 'One user per system', 'One login attempt allowed', 'B', 'SSO allows users to authenticate once and access multiple systems.', 'Access Control'),
('What is a biometric authentication factor?', 'Something you know', 'Something you have', 'Something you are', 'Somewhere you are', 'C', 'Biometrics are based on physical characteristics (something you are).', 'Access Control'),
('What is the purpose of account lockout policies?', 'Prevent password reuse', 'Prevent brute force attacks', 'Encrypt passwords', 'Monitor user activity', 'B', 'Account lockout prevents repeated login attempts (brute force attacks).', 'Access Control'),
('What is mandatory access control (MAC)?', 'User-controlled access', 'System-enforced access based on labels', 'Role-based access', 'Time-based access', 'B', 'MAC uses security labels and is enforced by the system, not users.', 'Access Control'),

-- Network Security (Domain 4)
('What OSI layer does a firewall primarily operate at?', 'Physical', 'Data Link', 'Network', 'Application', 'C', 'Traditional firewalls operate at the Network layer (Layer 3).', 'Network Security'),
('What is the purpose of a DMZ?', 'Store sensitive data', 'Isolate public-facing services', 'Encrypt traffic', 'Monitor employees', 'B', 'DMZ isolates public-facing services from the internal network.', 'Network Security'),
('What does a proxy server do?', 'Encrypts data', 'Acts as intermediary for requests', 'Stores backups', 'Monitors logs', 'B', 'Proxy servers act as intermediaries between clients and servers.', 'Network Security'),
('What is the purpose of network segmentation?', 'Increase network speed', 'Divide network into isolated sections', 'Reduce costs', 'Simplify management', 'B', 'Network segmentation divides networks to limit breach impact.', 'Network Security'),
('What protocol does HTTPS use for encryption?', 'IPSec', 'TLS/SSL', 'SSH', 'PPTP', 'B', 'HTTPS uses TLS (Transport Layer Security) for encryption.', 'Network Security'),
('What is a VPN used for?', 'Speed up internet', 'Create secure connection over public network', 'Block malware', 'Monitor traffic', 'B', 'VPNs create encrypted tunnels over public networks.', 'Network Security'),
('What does an IDS do?', 'Prevents all attacks', 'Detects and alerts on suspicious activity', 'Encrypts traffic', 'Blocks all traffic', 'B', 'IDS detects and alerts on potential security incidents.', 'Network Security'),
('What is the difference between IDS and IPS?', 'No difference', 'IPS can block threats, IDS only detects', 'IDS is faster', 'IPS is cheaper', 'B', 'IPS (Intrusion Prevention System) can actively block threats.', 'Network Security'),
('What port does HTTPS use by default?', '80', '443', '22', '3389', 'B', 'HTTPS uses port 443 by default.', 'Network Security'),
('What is port scanning used for?', 'Speed testing', 'Discovering open ports and services', 'Encrypting data', 'Backing up data', 'B', 'Port scanning identifies open ports and running services on a system.', 'Network Security'),

-- Incident Response (Domain 5)
('What is the first phase of incident response?', 'Containment', 'Preparation', 'Eradication', 'Recovery', 'B', 'Preparation is the first phase, establishing policies and procedures.', 'Incident Response'),
('What should be done immediately after detecting an incident?', 'Delete all logs', 'Contain the incident', 'Notify the media', 'Restart all systems', 'B', 'Containment prevents the incident from spreading.', 'Incident Response'),
('What is the purpose of evidence preservation?', 'Save disk space', 'Support legal proceedings and analysis', 'Speed up recovery', 'Reduce costs', 'B', 'Evidence preservation maintains integrity for investigation and legal use.', 'Incident Response'),
('What is chain of custody?', 'Management hierarchy', 'Documentation of evidence handling', 'Network topology', 'Backup schedule', 'B', 'Chain of custody documents who handled evidence and when.', 'Incident Response'),
('What should be included in an incident response plan?', 'Only technical procedures', 'Roles, procedures, and communication plans', 'Employee phone numbers', 'Budget information', 'B', 'IRP includes roles, procedures, communication, and escalation paths.', 'Incident Response'),
('What is the purpose of the lessons learned phase?', 'Assign blame', 'Improve future incident response', 'Calculate costs', 'Archive documents', 'B', 'Lessons learned identifies improvements for future incidents.', 'Incident Response'),
('What is a security incident?', 'Any IT problem', 'Event that threatens security', 'Scheduled maintenance', 'Software update', 'B', 'Security incidents are events that threaten confidentiality, integrity, or availability.', 'Incident Response'),
('Who should be notified during a security incident?', 'No one', 'Appropriate stakeholders per IRP', 'Everyone in company', 'Only IT staff', 'B', 'Notification follows the incident response plan and escalation procedures.', 'Incident Response'),
('What is forensic analysis?', 'Preventing incidents', 'Investigating and analyzing security incidents', 'Monitoring networks', 'Installing updates', 'B', 'Forensic analysis investigates incidents to understand what happened.', 'Incident Response'),
('What should be documented during incident response?', 'Nothing', 'All actions taken and findings', 'Only final results', 'Only costs', 'B', 'Comprehensive documentation supports analysis and legal requirements.', 'Incident Response'),

-- Security Operations (Domain 6)
('What is the purpose of security awareness training?', 'Teach programming', 'Educate users about security threats', 'Install software', 'Monitor networks', 'B', 'Security awareness training helps users recognize and respond to threats.', 'Security Operations'),
('What is a vulnerability assessment?', 'Exploiting vulnerabilities', 'Identifying security weaknesses', 'Installing patches', 'Monitoring logs', 'B', 'Vulnerability assessments identify potential security weaknesses.', 'Security Operations'),
('What is penetration testing?', 'Installing software', 'Simulating attacks to find vulnerabilities', 'User training', 'Backup testing', 'B', 'Penetration testing simulates real attacks to identify vulnerabilities.', 'Security Operations'),
('What is patch management?', 'Creating software', 'Applying security updates systematically', 'Monitoring networks', 'Training users', 'B', 'Patch management ensures systems are updated with security patches.', 'Security Operations'),
('What is the purpose of security logs?', 'Slow down systems', 'Record security events for analysis', 'Store user data', 'Backup files', 'B', 'Security logs record events for monitoring, analysis, and investigation.', 'Security Operations'),
('What is SIEM?', 'Security software', 'Security Information and Event Management', 'Network protocol', 'Encryption method', 'B', 'SIEM collects and analyzes security logs from multiple sources.', 'Security Operations'),
('What is configuration management?', 'Installing software', 'Maintaining secure system configurations', 'User training', 'Network monitoring', 'B', 'Configuration management ensures systems maintain secure settings.', 'Security Operations'),
('What is change management?', 'Changing passwords', 'Controlled process for system changes', 'Reorganizing teams', 'Updating documentation', 'B', 'Change management ensures changes are controlled and documented.', 'Security Operations'),
('What is the purpose of baseline configurations?', 'Maximum performance', 'Standard secure configuration', 'Minimum features', 'Cost reduction', 'B', 'Baselines define standard secure configurations for systems.', 'Security Operations'),
('What is security monitoring?', 'Installing cameras', 'Continuous observation of security events', 'User training', 'Backup verification', 'B', 'Security monitoring continuously observes systems for security events.', 'Security Operations'),

-- Risk Management (Domain 7)
('What is risk?', 'Any threat', 'Potential for loss or harm', 'Any vulnerability', 'Security control', 'B', 'Risk is the potential for loss or harm from a threat exploiting a vulnerability.', 'Risk Management'),
('What is a threat?', 'Security control', 'Potential cause of unwanted incident', 'Weakness in system', 'Risk level', 'B', 'A threat is anything that can exploit a vulnerability and cause harm.', 'Risk Management'),
('What is a vulnerability?', 'Security control', 'Threat source', 'Weakness that can be exploited', 'Risk assessment', 'C', 'A vulnerability is a weakness that can be exploited by a threat.', 'Risk Management'),
('What is risk assessment?', 'Eliminating all risks', 'Identifying and evaluating risks', 'Installing controls', 'Training users', 'B', 'Risk assessment identifies and evaluates risks to determine priorities.', 'Risk Management'),
('What is risk mitigation?', 'Accepting all risks', 'Reducing risk to acceptable level', 'Ignoring risks', 'Transferring all risks', 'B', 'Risk mitigation reduces risk through controls and countermeasures.', 'Risk Management'),
('What is risk acceptance?', 'Ignoring risk', 'Acknowledging and accepting risk level', 'Eliminating risk', 'Transferring risk', 'B', 'Risk acceptance is a conscious decision to accept a risk level.', 'Risk Management'),
('What is risk transfer?', 'Eliminating risk', 'Shifting risk to another party', 'Accepting risk', 'Reducing risk', 'B', 'Risk transfer shifts risk to another party (e.g., insurance).', 'Risk Management'),
('What is risk avoidance?', 'Accepting risk', 'Eliminating risk by not performing activity', 'Reducing risk', 'Transferring risk', 'B', 'Risk avoidance eliminates risk by not engaging in the risky activity.', 'Risk Management'),
('What is qualitative risk assessment?', 'Using numerical values', 'Using descriptive categories (high/medium/low)', 'Eliminating risks', 'Transferring risks', 'B', 'Qualitative assessment uses descriptive categories rather than numbers.', 'Risk Management'),
('What is quantitative risk assessment?', 'Using descriptive terms', 'Using numerical values and calculations', 'Accepting all risks', 'Avoiding all risks', 'B', 'Quantitative assessment uses numerical values to calculate risk.', 'Risk Management'),

-- Cryptography (Domain 8)
('What is symmetric encryption?', 'Different keys for encryption/decryption', 'Same key for encryption and decryption', 'No key needed', 'Public key only', 'B', 'Symmetric encryption uses the same key for both operations.', 'Cryptography'),
('What is asymmetric encryption?', 'Same key for both operations', 'Different keys for encryption/decryption', 'No encryption', 'Weak encryption', 'B', 'Asymmetric encryption uses a public key and private key pair.', 'Cryptography'),
('What is a hash function?', 'Encryption method', 'One-way function creating fixed-size output', 'Decryption method', 'Key exchange protocol', 'B', 'Hash functions create fixed-size outputs and are one-way (irreversible).', 'Cryptography'),
('What is a digital signature used for?', 'Encryption', 'Authentication and non-repudiation', 'Hashing', 'Key exchange', 'B', 'Digital signatures verify authenticity and provide non-repudiation.', 'Cryptography'),
('What is a certificate authority (CA)?', 'Encryption algorithm', 'Trusted entity issuing digital certificates', 'Hash function', 'Firewall', 'B', 'CAs issue and manage digital certificates for PKI.', 'Cryptography'),
('What is the purpose of a digital certificate?', 'Encrypt data', 'Bind public key to identity', 'Store passwords', 'Monitor traffic', 'B', 'Digital certificates bind public keys to identities.', 'Cryptography'),
('What is PKI?', 'Encryption algorithm', 'Public Key Infrastructure', 'Password system', 'Network protocol', 'B', 'PKI is the framework for managing public key encryption.', 'Cryptography'),
('What is the main advantage of asymmetric encryption?', 'Faster than symmetric', 'No need to share secret key', 'Simpler to implement', 'Uses less memory', 'B', 'Asymmetric encryption eliminates the need to securely share secret keys.', 'Cryptography'),
('What is a key exchange protocol?', 'Encryption method', 'Method to securely share keys', 'Hash function', 'Digital signature', 'B', 'Key exchange protocols allow secure sharing of encryption keys.', 'Cryptography'),
('What does hashing provide?', 'Confidentiality', 'Integrity verification', 'Availability', 'Authorization', 'B', 'Hashing verifies data integrity by detecting changes.', 'Cryptography'),

-- Additional questions to reach 100
('What is social engineering?', 'Network engineering', 'Manipulating people to divulge information', 'Software development', 'System administration', 'B', 'Social engineering manipulates people into revealing sensitive information.', 'Security Principles'),
('What is phishing?', 'Network scanning', 'Fraudulent attempt to obtain sensitive information', 'Legitimate email', 'Firewall technique', 'B', 'Phishing uses deceptive emails to trick users into revealing information.', 'Security Principles'),
('What is malware?', 'Security software', 'Malicious software', 'Network protocol', 'Encryption method', 'B', 'Malware is software designed to harm or exploit systems.', 'Security Principles'),
('What is ransomware?', 'Backup software', 'Malware that encrypts data for ransom', 'Antivirus program', 'Firewall', 'B', 'Ransomware encrypts data and demands payment for decryption.', 'Security Principles'),
('What is a zero-day vulnerability?', 'Old vulnerability', 'Unknown vulnerability with no patch', 'Patched vulnerability', 'Low-risk vulnerability', 'B', 'Zero-day vulnerabilities are unknown to vendors and have no patches.', 'Security Principles'),
('What is the principle of separation of duties?', 'One person does everything', 'Critical tasks divided among multiple people', 'All tasks automated', 'Managers do all tasks', 'B', 'Separation of duties prevents fraud by dividing critical tasks.', 'Security Principles'),
('What is data classification?', 'Organizing files', 'Categorizing data by sensitivity', 'Encrypting data', 'Backing up data', 'B', 'Data classification categorizes data based on sensitivity and value.', 'Security Principles'),
('What is the purpose of data retention policies?', 'Keep all data forever', 'Define how long to keep data', 'Delete all data immediately', 'Encrypt all data', 'B', 'Data retention policies specify how long to retain different data types.', 'Security Principles'),
('What is data sanitization?', 'Cleaning keyboards', 'Securely erasing data', 'Organizing files', 'Backing up data', 'B', 'Data sanitization securely erases data to prevent recovery.', 'Security Principles'),
('What is the purpose of security policies?', 'Technical implementation', 'Define security rules and expectations', 'Install software', 'Monitor networks', 'B', 'Security policies define organizational security rules and expectations.', 'Security Principles'),
('What is an acceptable use policy?', 'Technical specification', 'Rules for using organizational resources', 'Network diagram', 'Backup schedule', 'B', 'AUP defines acceptable use of organizational IT resources.', 'Security Principles'),
('What is the purpose of security awareness?', 'Technical training', 'Educate users about security responsibilities', 'Install software', 'Monitor systems', 'B', 'Security awareness educates users about their security responsibilities.', 'Security Principles'),
('What is tailgating?', 'Following cars', 'Unauthorized person following authorized person through secure door', 'Network attack', 'Malware type', 'B', 'Tailgating is physical security breach by following authorized persons.', 'Security Principles'),
('What is shoulder surfing?', 'Sports activity', 'Observing someone enter sensitive information', 'Network monitoring', 'Backup method', 'B', 'Shoulder surfing is observing someone to obtain sensitive information.', 'Security Principles'),
('What is dumpster diving?', 'Recycling program', 'Searching trash for sensitive information', 'Backup method', 'Network attack', 'B', 'Dumpster diving searches discarded materials for sensitive information.', 'Security Principles'),
('What is pretexting?', 'Writing documentation', 'Creating false scenario to obtain information', 'Network configuration', 'Backup strategy', 'B', 'Pretexting uses fabricated scenarios to manipulate victims.', 'Security Principles'),
('What is baiting?', 'Fishing', 'Leaving malware-infected device to be found', 'Network monitoring', 'Backup testing', 'B', 'Baiting lures victims with promise of something desirable.', 'Security Principles'),
('What is quid pro quo?', 'Legal term', 'Offering service in exchange for information', 'Network protocol', 'Encryption method', 'B', 'Quid pro quo offers service or benefit in exchange for information.', 'Security Principles'),
('What is spear phishing?', 'Generic phishing', 'Targeted phishing attack', 'Legitimate email', 'Antivirus software', 'B', 'Spear phishing targets specific individuals or organizations.', 'Security Principles'),
('What is whaling?', 'Network attack', 'Phishing targeting high-level executives', 'Malware type', 'Firewall technique', 'B', 'Whaling targets high-level executives with phishing attacks.', 'Security Principles');
